routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//antivirus Routes
Route::group(['middleware' => ['web', 'log']], function () {

    Route::get('/', 'IndexController@home')->name('index.index');

    Route::get('{antivirus}/license', 'IndexController@license')->name('menu.license');
    Route::get('{antivirus}/download', 'IndexController@download')->name('menu.download');
    Route::get('{antivirus}/learn', 'IndexController@learn')->name('menu.learn');
    Route::get('{antivirus}/comments', 'IndexController@comments')->name('menu.comments');
    Route::get('{antivirus}/star-comments', 'IndexController@starComments')->name('menu.starComments');
    Route::get('{antivirus}/aboutantivirus', 'IndexController@aboutAntivirus')->name('menu.aboutAntivirus');
    Route::get('{antivirus}/noghate-ghovat', 'IndexController@noghatGhovat')->name('menu.noghatGhovat');
    Route::get('{antivirus}/compare-antivirus', 'IndexController@compareAntivirus')->name('menu.compareAntivirus');

    Route::get('{posts}/post', 'IndexController@post');

    Route::get('upload', 'IndexController@uploadGet')->name('upload.get');
    Route::post('upload', 'IndexController@uploadPost')->name('upload.post');

    Route::get('scaffold-dashboard', 'IndexController@dashboard');

    Route::get('vip/verifym', 'ZarinController@verifyMontyly')->name('payment.verify.monthly');
    Route::get('vip/verifyy', 'ZarinController@verifyYearly')->name('payment.verify.yearly');
    Route::get('vip/price', 'ZarinController@create')->name('payment.buy');
    Route::get('vip/planm', 'ZarinController@planMonthly')->name('payment.monthly');
    Route::get('vip/plany', 'ZarinController@planYearly')->name('payment.yearly');

    Route::get('compare/new', 'IndexController@compareAll')->name('compare.all');
    Route::get('best-antivirus/new', 'IndexController@bestAntivirus')->name('best.antivirus');

    Route::resource('karbar', 'KarbarController');

    Route::match(['GET', 'POST'], 'adminAddVip', 'AdminController@adminAddVip')->name('adminAddVip');

    Route::resource('antivirus', 'AntivirusController');

    Route::resource('post', '\App\Http\Controllers\PostController');
    Route::post('post/{id}/storeCPost', '\App\Http\Controllers\PostController@storeCPost')->name('post.store.cpost');//store posts as comments storeCPost
    Route::patch('post/{id}/updateCPost', '\App\Http\Controllers\PostController@updateCPost')->name('post.update.cpost');//update posts as comments updateCPost
    Route::patch('post/{post}/votePositive', 'PostController@votePositive')->name('post.positive');// like post
    Route::patch('post/{post}/voteNegative', 'PostController@voteNegative')->name('post.negative');// unlike post
    Route::post('post/{id}/update', '\App\Http\Controllers\PostController@update');
    Route::get('post/{id}/delete', '\App\Http\Controllers\PostController@destroy');
    Route::get('post/{id}/deleteMsg', '\App\Http\Controllers\PostController@DeleteMsg');

    Route::resource('category', '\App\Http\Controllers\CategoryController');
    Route::post('category/{id}/update', '\App\Http\Controllers\CategoryController@update');
    Route::get('category/{id}/delete', '\App\Http\Controllers\CategoryController@destroy');
    Route::get('category/{id}/deleteMsg', '\App\Http\Controllers\CategoryController@DeleteMsg');

    Route::resource('comment', '\App\Http\Controllers\CommentController');
    Route::patch('comment/{comment}/editlite', 'CommentController@liteUpdate')->name('comment.lite.update');
    Route::post('comment/{id}/update', '\App\Http\Controllers\CommentController@update');
    Route::get('comment/{id}/delete', '\App\Http\Controllers\CommentController@destroy');
    Route::get('comment/{id}/deleteMsg', '\App\Http\Controllers\CommentController@DeleteMsg');

    Route::resource('license', '\App\Http\Controllers\LicenseController');
    Route::post('license/{id}/update', '\App\Http\Controllers\LicenseController@update');
    Route::get('license/{id}/delete', '\App\Http\Controllers\LicenseController@destroy');
    Route::get('license/{id}/deleteMsg', '\App\Http\Controllers\LicenseController@DeleteMsg');

    Route::resource('tag', '\App\Http\Controllers\TagController');
    Route::post('tag/{id}/update', '\App\Http\Controllers\TagController@update');
    Route::get('tag/{id}/delete', '\App\Http\Controllers\TagController@destroy');
    Route::get('tag/{id}/deleteMsg', '\App\Http\Controllers\TagController@DeleteMsg');

    Route::resource('vote', '\App\Http\Controllers\VoteController');
    Route::post('vote/{id}/update', '\App\Http\Controllers\VoteController@update');
    Route::get('vote/{id}/delete', '\App\Http\Controllers\VoteController@destroy');
    Route::get('vote/{id}/deleteMsg', '\App\Http\Controllers\VoteController@DeleteMsg');

    Route::resource('log', '\App\Http\Controllers\LogController');
    Route::post('log/{id}/update', '\App\Http\Controllers\LogController@update');
    Route::get('log/{id}/delete', '\App\Http\Controllers\LogController@destroy');
    Route::get('log/{id}/deleteMsg', '\App\Http\Controllers\LogController@DeleteMsg');

    Auth::routes();

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('coznet/list', 'CoznetListController@listGet')->name('coznet.get');
    Route::patch('cozne/update/{id}', 'CoznetListController@updateAuto')->name('license.update.auto');
    Route::patch('coznet/list', 'CoznetListController@listPost')->name('coznet.post');
    Route::get('coznet/{id}', 'CoznetController@create')->name('coznet.create');
});

app/Http/Controllers/ScaffoldInterface/AppController.php
<?php

namespace App\Http\Controllers\ScaffoldInterface;

use App\Http\Controllers\Controller;

/**
 * Class AppController.
 *
 * @author Amrani Houssain <amranidev@gmail.com>
 */
class AppController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function dashboard()
    {
        $this->authorize('is-admin');

        $users = \App\User::all()->count();
//        $roles = \Spatie\Permission\Models\Role::all()->count();
//        $permissions = \Spatie\Permission\Models\Permission::all()->count();
//        $entities = \Amranidev\ScaffoldInterface\Models\Scaffoldinterface::all();

        return view('scaffold-interface.dashboard.dashboard', compact('users', 'roles', 'permissions', 'entities'));
    }
}

app/Http/Controllers/ScaffoldInterface/PermissionController.php
<?php

namespace App\Http\Controllers\ScaffoldInterface;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;

class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('is-admin');

        $permissions = Permission::all();

        return view('scaffold-interface.permissions.index', compact('permissions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('scaffold-interface.permissions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('is-admin');

        Permission::create(['name' => $request->name]);

        return redirect('scaffold-permissions');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->authorize('is-admin');

        $permission = Permission::findOrFail($id);

        return view('scaffold-interface.permissions.edit', compact('permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $this->authorize('is-admin');

        $permission = Permission::findOrFail($request->permission_id);

        $permission->name = $request->name;

        $permission->update();

        return redirect('scaffold-permissions');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->authorize('is-admin');

        $permission = Permission::findOrFail($id);

        $permission->delete();

        return redirect('scaffold-permissions');
    }
}

app/Http/Controllers/ScaffoldInterface/RoleController.php
<?php

namespace App\Http\Controllers\ScaffoldInterface;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('is-admin');

        $roles = Role::all();

        return view('scaffold-interface.roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('scaffold-interface.roles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('is-admin');

        Role::create(['name' => $request->name]);

        return redirect('scaffold-roles');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::findOrFail($id);

        return view('scaffold-interface.roles.edit', compact('role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $this->authorize('is-admin');

        $role = Role::findOrFail($request->role_id);

        $role->name = $request->name;

        $role->update();

        return redirect('scaffold-roles');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->authorize('is-admin');

        $role = Role::findOrFail($id);

        $role->delete();

        return redirect('scaffold-roles');
    }
}

app/Http/Controllers/ScaffoldInterface/UserController.php
<?php

namespace App\Http\Controllers\ScaffoldInterface;

use App\Http\Controllers\Controller;
use Hash;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('is-admin');

        $users = \App\User::all();

        return view('scaffold-interface.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('scaffold-interface.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('is-admin');

        $user = new \App\User();

        $user->email = $request->email;
        $user->name = $request->name;
        $user->password = Hash::make($request->password);
        $user->image = 'AnonymousMale.jpg';

        $user->save();

        return redirect('scaffold-users');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->authorize('is-admin');

        $user = \App\User::findOrfail($id);
        $roles = Role::all()->pluck('name');
        $roles = \DB::table('roles')->pluck('name');
//        $permissions = '';
        $userRoles = $user->role_id;
//        $userPermissions = $user->permissions;

        return view('karbar.edit', compact('user', 'roles', 'userRoles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $this->authorize('is-admin');

        $user = \App\User::findOrfail($request->user_id);

        $user->email = $request->email;
        $user->name = $request->name;
        $user->password = Hash::make($request->password);

        $user->save();

        return redirect('scaffold-users');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->authorize('is-admin');

        $user = \App\User::findOrfail($id);

        $user->delete();

        return redirect('scaffold-users');
    }

    /**
     * Assign Role to user.
     *
     * @param \Illuminate\Http\Request
     *
     * @return \Illuminate\Http\Response
     */
    public function addRole(Request $request)
    {
        $this->authorize('is-admin');

        $user = \App\User::findOrfail($request->user_id);
        $user->assignRole($request->role_name);

        return redirect('scaffold-users/edit/'.$request->user_id);
    }

    /**
     * Assign Permission to a user.
     *
     * @param \Illuminate\Http\Request
     *
     * @return \Illuminate\Http\Response
     */
    public function addPermission(Request $request)
    {
        $this->authorize('is-admin');

        $user = \App\User::findorfail($request->user_id);
        $user->givePermissionTo($request->permission_name);

        return redirect('scaffold-users/edit/'.$request->user_id);
    }

    /**
     * revoke Permission to a user.
     *
     * @param \Illuminate\Http\Request
     *
     * @return \Illuminate\Http\Response
     */
    public function revokePermission($permission, $user_id)
    {
        $this->authorize('is-admin');

        $user = \App\User::findorfail($user_id);

        $user->revokePermissionTo(str_slug($permission, ' '));

        return redirect('scaffold-users/edit/'.$user_id);
    }

    /**
     * revoke Role to a a user.
     *
     * @param \Illuminate\Http\Request
     *
     * @return \Illuminate\Http\Response
     */
    public function revokeRole($role, $user_id)
    {
        $this->authorize('is-admin');

        $user = \App\User::findorfail($user_id);

        $user->removeRole(str_slug($role, ' '));

        return redirect('scaffold-users/edit/'.$user_id);
    }
}

resources/views/scaffold-interface/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@yield('title')</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{asset('bower_components/bootstrap-rtl/dist/css/bootstrap-rtl.min.css')}}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    {{--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.5/css/AdminLTE.min.css">--}}
    <link rel="stylesheet" href="{{asset('css/scaffold-interface-css/AdminLTE.min.css')}}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
    folder instead of downloading all of them to reduce the load. -->

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.5/css/skins/_all-skins.min.css">
    <!--Let browser know website is optimized for mobile-->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->


    @stack('header')
</head>
<body class="hold-transition skin-blue sidebar-mini rtl">
<div class="wrapper">
    <header class="main-header">
        <!-- Logo -->
        <a href="{{url('scaffold-dashboard')}}" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>S</b>IN</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>پنل کاربری</b></span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">تغییر ناوبری</span>
            </a>
            <div class="navbar-custom-menu ">
                <ul class="nav navbar-nav">
                    <!-- Notification Navbar List-->
                    <li class="dropdown notifications-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bell-o"></i>
                            <span class="label notification-label">new</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">اعلامیه ها</li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu notification-menu">
                                </ul>
                            </li>
                            <li class="footer"><a href="#">دیدن همه</a></li>
                        </ul>
                    </li>
                    <!-- END notification navbar list-->
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="http://ahloman.net/wp-content/uploads/2013/06/user.jpg" class="user-image"
                                 alt="User Image">
                            <span class="hidden-xs">{{Auth::user()->name}}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="http://ahloman.net/wp-content/uploads/2013/06/user.jpg" class="img-circle"
                                     alt="User Image">
                                <p>
                                    {{Auth::user()->name}}
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-right">
                                    <a href="{{url('logout')}}" class="btn btn-default btn-flat"
                                       onclick="event.preventDefault();
											document.getElementById('logout-form').submit();">خروج</a>
                                    <form id="logout-form" action="{{ url('/logout') }}" method="POST"
                                          style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- search form -->
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
								<button type="submit" name="search" id="search-btn" class="btn btn-flat"><i
                                            class="fa fa-search"></i>
								</button>
							</span>
                </div>
            </form>
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu">
                <li class="header"><b>ناوبری اصلی</b></li>
                <li class="treeview">
                    <a href="{{url('scaffold-dashboard')}}">
                        <i class="fa fa-dashboard"></i> <span>داشبورد</span></i>
                    </a>
                </li>
                <li class="treeview">
                    <a href="{{url('/')}}">
                        <i class="fa fa-home"></i> <span>وبسایت</span></i>
                    </a>
                </li>
                <li class="treeview">
                    <a href="{{url('/upload')}}">
                        <i class="fa fa-upload"></i> <span>آپلود</span></i>
                    </a>
                </li>
                <li class="header"><b>ناوبری ادمین</b></li>
                <li class="treeview"><a href="{{url('/karbar')}}"><i class="fa fa-users"></i>
                        <span>یوزر ها</span></a></li>
                <li class="treeview"><a href="{{url('/scaffold')}}"><i class="fa fa-user-secret"></i>
                        <span>داربست</span></a></li>
                <li class="header"><b>ناوبری یوزر ها</b></li>
                <li class="treeview"><a href="{{route('antivirus.index')}}"><i class="fa fa-desktop"></i> <span>آنتی ویروس ها</span></a></li>
                <li class="treeview"><a href="{{route('license.index')}}"><i class="fa fa-desktop"></i> <span>لایسنس ها</span></a></li>
                <li class="treeview"><a href="{{route('post.index')}}"><i class="fa fa-desktop"></i> <span>پست ها</span></a></li>
                <li class="treeview"><a href="{{route('adminAddVip')}}"><i class="fa fa-desktop"></i> <span>اکانت ویژه</span></a></li>
                <li class="treeview"><a href="{{route('category.index')}}"><i class="fa fa-desktop"></i> <span>دسته بندی ها</span></a></li>
                <li class="treeview"><a href="{{route('comment.index')}}"><i class="fa fa-desktop"></i> <span>دیدگاه ها</span></a></li>
                <li class="treeview"><a href="{{route('tag.index')}}"><i class="fa fa-desktop"></i> <span>برچسب ها</span></a></li>
                <li class="treeview"><a href="{{route('log.index')}}"><i class="fa fa-desktop"></i> <span>لوگ ها</span></a></li>
                <li class="treeview"><a href="{{route('vote.index')}}"><i class="fa fa-desktop"></i> <span>امتیاز ها</span></a></li>
            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>
    <div class="content-wrapper">
        @yield('content')
    </div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class='AjaxisModal'>
    </div>
</div>
<!-- Compiled and minified JavaScript -->
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.5/js/app.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.5/js/demo.js"></script>
<script> var baseURL = "{{ URL::to('/') }}"</script>
<script src="{{URL::asset('js/AjaxisBootstrap.js') }}"></script>
<script src="{{URL::asset('js/scaffold-interface-js/customA.js') }}"></script>
<script src="https://js.pusher.com/3.2/pusher.min.js"></script>
<script>
    // pusher log to console.
    Pusher.logToConsole = true;
    // here is pusher client side code.
    var pusher = new Pusher("{{env("PUSHER_APP_KEY")}}", {
        encrypted: true
    });
    var channel = pusher.subscribe('test-channel');
    channel.bind('test-event', function (data) {
        // display message coming from server on dashboard Notification Navbar List.
        $('.notification-label').addClass('label-warning');
        $('.notification-menu').append(
            '<li>\
                <a href="#">\
                    <i class="fa fa-users text-aqua"></i> ' + data.message + '\
				</a>\
			</li>'
        );
    });
</script>

@stack('footer')
</body>
</html>

resources/views/scaffold-interface/layouts/defaultMaterialize.blade.php
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/css/materialize.min.css">
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<!--Let browser know website is optimized for mobile-->
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<title>@yield('title')</title>
	</head>
	<body>
		@yield('content')
		<div id="modal1" class="modal">
			<div class = "row AjaxisModal">
			</div>
		</div>
		<script src = "https://code.jquery.com/jquery-2.1.1.min.js"></script>
		<script src = "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/js/materialize.min.js"></script>
		<script>  var baseURL = "{{ URL::to('/') }}"</script>
		<script src = "{{URL::asset('js/AjaxisMaterialize.js')}}"></script>
		<script src = "{{URL::asset('js/scaffold-interface-js/customA.js')}}"></script>
		<script>
		$('select').material_select();
		</script>
	</body>
</html>