routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//antivirus Routes
Route::group(['middleware' => ['web', 'log']], function () {

    Route::get('/', 'IndexController@home')->name('index.index');

    Route::get('{antivirus}/license', 'IndexController@license')->name('menu.license');
    Route::get('{antivirus}/download', 'IndexController@download')->name('menu.download');
    Route::get('{antivirus}/learn', 'IndexController@learn')->name('menu.learn');
    Route::get('{antivirus}/comments', 'IndexController@comments')->name('menu.comments');
    Route::get('{antivirus}/star-comments', 'IndexController@starComments')->name('menu.starComments');
    Route::get('{antivirus}/aboutantivirus', 'IndexController@aboutAntivirus')->name('menu.aboutAntivirus');
    Route::get('{antivirus}/noghate-ghovat', 'IndexController@noghatGhovat')->name('menu.noghatGhovat');
    Route::get('{antivirus}/compare-antivirus', 'IndexController@compareAntivirus')->name('menu.compareAntivirus');

    Route::get('{posts}/post', 'IndexController@post');

    Route::get('upload', 'IndexController@uploadGet')->name('upload.get');
    Route::post('upload', 'IndexController@uploadPost')->name('upload.post');

    Route::get('scaffold-dashboard', 'IndexController@dashboard');

    Route::get('vip/verifym', 'ZarinController@verifyMontyly')->name('payment.verify.monthly');
    Route::get('vip/verifyy', 'ZarinController@verifyYearly')->name('payment.verify.yearly');
    Route::get('vip/price', 'ZarinController@create')->name('payment.buy');
    Route::get('vip/planm', 'ZarinController@planMonthly')->name('payment.monthly');
    Route::get('vip/plany', 'ZarinController@planYearly')->name('payment.yearly');

    Route::get('compare/new', 'IndexController@compareAll')->name('compare.all');
    Route::get('best-antivirus/new', 'IndexController@bestAntivirus')->name('best.antivirus');

    Route::resource('karbar', 'KarbarController');

    Route::match(['GET', 'POST'], 'adminAddVip', 'AdminController@adminAddVip')->name('adminAddVip');

    Route::resource('antivirus', 'AntivirusController');

    Route::resource('post', '\App\Http\Controllers\PostController');
    Route::post('post/{id}/storeCPost', '\App\Http\Controllers\PostController@storeCPost')->name('post.store.cpost');//store posts as comments storeCPost
    Route::patch('post/{id}/updateCPost', '\App\Http\Controllers\PostController@updateCPost')->name('post.update.cpost');//update posts as comments updateCPost
    Route::patch('post/{post}/votePositive', 'PostController@votePositive')->name('post.positive');// like post
    Route::patch('post/{post}/voteNegative', 'PostController@voteNegative')->name('post.negative');// unlike post
    Route::post('post/{id}/update', '\App\Http\Controllers\PostController@update');
    Route::get('post/{id}/delete', '\App\Http\Controllers\PostController@destroy');
    Route::get('post/{id}/deleteMsg', '\App\Http\Controllers\PostController@DeleteMsg');

    Route::resource('category', '\App\Http\Controllers\CategoryController');
    Route::post('category/{id}/update', '\App\Http\Controllers\CategoryController@update');
    Route::get('category/{id}/delete', '\App\Http\Controllers\CategoryController@destroy');
    Route::get('category/{id}/deleteMsg', '\App\Http\Controllers\CategoryController@DeleteMsg');

    Route::resource('comment', '\App\Http\Controllers\CommentController');
    Route::patch('comment/{comment}/editlite', 'CommentController@liteUpdate')->name('comment.lite.update');
    Route::post('comment/{id}/update', '\App\Http\Controllers\CommentController@update');
    Route::get('comment/{id}/delete', '\App\Http\Controllers\CommentController@destroy');
    Route::get('comment/{id}/deleteMsg', '\App\Http\Controllers\CommentController@DeleteMsg');

    Route::resource('license', '\App\Http\Controllers\LicenseController');
    Route::post('license/{id}/update', '\App\Http\Controllers\LicenseController@update');
    Route::get('license/{id}/delete', '\App\Http\Controllers\LicenseController@destroy');
    Route::get('license/{id}/deleteMsg', '\App\Http\Controllers\LicenseController@DeleteMsg');

    Route::resource('tag', '\App\Http\Controllers\TagController');
    Route::post('tag/{id}/update', '\App\Http\Controllers\TagController@update');
    Route::get('tag/{id}/delete', '\App\Http\Controllers\TagController@destroy');
    Route::get('tag/{id}/deleteMsg', '\App\Http\Controllers\TagController@DeleteMsg');

    Route::resource('vote', '\App\Http\Controllers\VoteController');
    Route::post('vote/{id}/update', '\App\Http\Controllers\VoteController@update');
    Route::get('vote/{id}/delete', '\App\Http\Controllers\VoteController@destroy');
    Route::get('vote/{id}/deleteMsg', '\App\Http\Controllers\VoteController@DeleteMsg');

    Route::resource('log', '\App\Http\Controllers\LogController');
    Route::post('log/{id}/update', '\App\Http\Controllers\LogController@update');
    Route::get('log/{id}/delete', '\App\Http\Controllers\LogController@destroy');
    Route::get('log/{id}/deleteMsg', '\App\Http\Controllers\LogController@DeleteMsg');

    Auth::routes();

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('coznet/list', 'CoznetListController@listGet')->name('coznet.get');
    Route::patch('cozne/update/{id}', 'CoznetListController@updateAuto')->name('license.update.auto');
    Route::patch('coznet/list', 'CoznetListController@listPost')->name('coznet.post');
    Route::get('coznet/{id}', 'CoznetController@create')->name('coznet.create');
});

resources/views/index/bestAntivirus.blade.php
    <div style="height: 96vh;width: 100%;">
        <iframe height="100%" width="100%" src="//www.toptenreviews.com/software/security/best-antivirus-software/"></iframe>
    </div>

resources/views/index/compareAll.blade.php
@extends('layouts.layout')
@section('content')

    <div style="height: 10vh;width: 100%">
        @include('partials.header')
    </div>

    <div style="height: 86vh;width: 100%;">
        <iframe height="100%" width="100%" src="https://chart.av-comparatives.org/chart1.php"></iframe>
    </div>

@endsection

resources/views/index/index.blade.php
@extends('layouts.layout')
@section('content')

    @include('partials.header')

    @include('partials.sliderMain')

    @include('partials.antivirusesImage')




    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="cta-area wow fadeInUp " >
                    <h3>مقایسه آنتی ویروس ها</h3>
                    <p>مقایسه همه آنتی ویروس ها در سرعت و قدرت</p>
                    <a href="{{ route('compare.all') }}" target="_blank" class="boxed-btn cta-btn">مقایسه کنید</a>
                </div>
            </div>
        </div>
    </div>

    <div class="content-block">
        <div class="container">
            <div class="row">
                <div class="col-md-4 wow fedeInLeft">
                    <h3>لیست بهترین آنتی ویروس های سال</h3>
                    <p>بهترین آنتی ویروس های امسال رو بهتون معرفی میکنیم. مقایسه از نظر قدرت آنتی ویروس و سرعت آن انجام شده...</p>
                    <a href="{{ route('best.antivirus') }}" target="_blank" class="readmore-btn">ادامه مطلب...  <i class="fa fa-angle-left"></i></a>
                </div>
                <div class="col-md-4 text-center wow fadeInUp">
                    <img src="uploads/files/sadegh/1514659381sayer.jpg" alt="" class="img-rounded about-icon-img">
                </div>
                <div class="col-md-4 wow fadeInRight">
                    <h3>کدام آنتی ویروس را انتخاب کنم؟</h3>
                    <p>پیش از این در قسمت مقایسه انتی ویروس های کامپیوتر, به تست و بررسی قدرت و سرعت و … انتی ویروس ها پرداختیم...</p>
                    <a href="{{ route('index.index') }}/مقایسه انتی ویروس ها از نگاه ما/post" target="_blank" class="readmore-btn">ادامه مطلب...  <i class="fa fa-angle-left"></i></a>
                </div>
            </div>
        </div>
    </div>

    <div class="content-block gray-bg padidng-bottom-0 wow fadeIn">
        <img src="assets/img/man.png" class="bg-left" alt="">
        <div class="container">
            <div class="row">
                <div class="col-md-5 col-md-offset-7">
                    <h3>درباره ما</h3>

                    <div class="mega-faqs-wrapper">
                        <div class="mega-single-faq">
                            <p>
                                - دانلود جدیدترین ورژن هر آنتی ویروس
                            </p>
                            <p>
                                - دسترسی به لایسنس هر آنتی ویروس(اعضای ویژه)
                            </p>
                            <p>
                                - آموزش فعال سازی آنتی ویروس ها
                            </p>
                            <p>
                                - آموزش کار کردن با آنتی ویروس ها
                            </p>
                            <p>
                                - پاسخ سریع به مشکلات شما
                            </p>
                            <p>
                                - محلی برای پرسش و پاسخ و بحث و گفت و گو
                            </p>
                            <p>
                                - مقایسه آنتی ویروس ها جهت انتخاب آنتی ویروس مناسب
                            </p>
                            <p>
                                - معرفی بهترین آنتی ویروس های اندروید همراه با لینک دانلود جدیدترین نسخه هر آنتی ویروس
                            </p>
                            {{--<h4>- How you keep my information secure?</h4>--}}
                            {{--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet sequi placeat beatae neque, officiis repudiandae totam quia, consectetur, soluta adipisci asperiores! Obcaecati unde nihil atque accusamus odit consequuntur suscipit?</p>--}}
                        {{--</div>--}}
                        {{--<div class="mega-single-faq">--}}
                            {{--<h4>- How can I remove information?</h4>--}}
                            {{--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet sequi placeat beatae neque, officiis repudiandae totam quia, consectetur, soluta adipisci asperiores! Obcaecati unde nihil atque accusamus odit consequuntur suscipit?</p>--}}

                            {{--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati reiciendis ut quis laboriosam pariatur repellendus laudantium tempora voluptatem, veniam sequi.</p>--}}
                        {{--</div>--}}
                        {{--<div class="mega-single-faq">--}}
                            {{--<h4>- How do I find my Windows product key?</h4>--}}
                            {{--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus eveniet sequi placeat beatae neque, officiis repudiandae totam quia, consectetur, soluta adipisci asperiores! Obcaecati unde nihil atque accusamus odit consequuntur suscipit?</p>--}}
                        </div>
                    </div>

                    {{--<p class="text-right">Question not listed here? <a href="">Click here ask a question</a></p>--}}
                    {{--<div class="spacer-30"></div>--}}
                </div>
            </div>
        </div>
    </div>

    {{--<div class="content-block wow fadeIn">--}}
        {{--<div class="container">--}}
            {{--<div class="row">--}}
                {{--<div class="col-md-12">--}}
                    {{--<h3 class="text-center">Customers loves us for our work.<br/> Here are some valuable comments.</h3>--}}

                    {{--<div class="testimonial-carousel">--}}
                        {{--<div class="single-testimonial-item">--}}
                            {{--<div class="testimonial-content">--}}
                                {{--<p>In on announcing if of comparison pianoforte projection. Maidsgay yet bed asked blind dried point. On abroad danger likely regretedward do. Too horrible consider followed may differed age.</p>--}}
                            {{--</div>--}}

                            {{--<div class="testimonial-author-info">--}}
                                {{--<img src="assets/img/author.jpg" alt="">--}}
                                {{--<h4>James Cameron</h4>--}}
                                {{--CEO, Open Work Challenge--}}
                            {{--</div>--}}
                        {{--</div>--}}
                        {{--<div class="single-testimonial-item">--}}
                            {{--<div class="testimonial-content">--}}
                                {{--<p>In on announcing if of comparison pianoforte projection. Maidsgay yet bed asked blind dried point. On abroad danger likely regretedward do. Too horrible consider followed may differed age.</p>--}}
                            {{--</div>--}}

                            {{--<div class="testimonial-author-info">--}}
                                {{--<img src="assets/img/author-2.jpg" alt="">--}}
                                {{--<h4>John Doe</h4>--}}
                                {{--Marketing Officer, Open Work Challenge--}}
                            {{--</div>--}}
                        {{--</div>--}}
                        {{--<div class="single-testimonial-item">--}}
                            {{--<div class="testimonial-content">--}}
                                {{--<p>In on announcing if of comparison pianoforte projection. Maidsgay yet bed asked blind dried point. On abroad danger likely regretedward do. Too horrible consider followed may differed age.</p>--}}
                            {{--</div>--}}

                            {{--<div class="testimonial-author-info">--}}
                                {{--<img src="assets/img/author.jpg" alt="">--}}
                                {{--<h4>James Cameron</h4>--}}
                                {{--CEO, Open Work Challenge--}}
                            {{--</div>--}}
                        {{--</div>--}}
                    {{--</div>--}}
                {{--</div>--}}
            {{--</div>--}}
        {{--</div>--}}
    {{--</div>--}}



    <div class="content-block">
        <div class="container">

            @php
                $i = 0;
            @endphp
            @foreach($posts as $post)
                @if($i % 3 == 0)
                    <div class="row">
                @endif
                    <div class="col-sm-4">
                        <div class="single-service-item wow fadeInUp" style="border-top: 3px solid #1360F4">
                            @if(isset($post->type->name))
                                <span style="font-size: x-large ">{{ $post->type->name }} - {{ $post->antivirus->name }}</span>
                            @else
                                <span style="font-size: x-large ">دیدگاه</span>
                            @endif
                            <p>{!! strip_tags(substr($post->text, 0, 100)) !!}</p>
                            <a href="/{{ $post->id }}/post" class="readmore-btn">ادامه مطلب...  <i class="fa fa-angle-left"></i></a>
                        </div>
                    </div>
                @if($i % 3 == 2)
                    </div>
                @endif
                @php
                    $i++;
                @endphp
            @endforeach
            @if($i % 3 != 3)
                </div>
            @endif

                {{--<div class="col-sm-4">--}}
                    {{--<div class="single-service-item wow fadeInUp" data-wow-delay="1.1s">--}}
                        {{--<h3>fdgfdgfdgfdgfdgfdg</h3>--}}
                        {{--<p>fgdfgdfgdfsgfdgsdfgfgdfsgfdg.</p>--}}
                        {{--<a href="/11/post" class="readmore-btn">ادامه مطلب...  <i class="fa fa-angle-left"></i></a>--}}
                    {{--</div>--}}
                {{--</div>--}}
                {{--<div class="col-sm-4">--}}
                    {{--<div class="single-service-item wow fadeInUp" data-wow-delay="1.2s">--}}
                        {{--<h3>App Development</h3>--}}
                        {{--<p>Our awesome members are ready to create your dream website project with passion and dedication.</p>--}}
                        {{--<a href="single-service-agency.html" class="readmore-btn">ادامه مطلب...  <i class="fa fa-angle-left"></i></a>--}}
                    {{--</div>--}}
                {{--</div>--}}
            {{--</div>--}}
            {{--<div class="specer-70 hidden-xs"></div>--}}
            {{--<div class="row">--}}
                {{--<div class="col-sm-4">--}}
                    {{--<div class="single-service-item wow fadeInUp" data-wow-delay="1.3s">--}}
                        {{--<h3>Social Media Marketing</h3>--}}
                        {{--<p>Our awesome members are ready to create your dream website project with passion and dedication.</p>--}}
                        {{--<a href="single-service-agency.html" class="readmore-btn">ادامه مطلب...  <i class="fa fa-angle-left"></i></a>--}}
                    {{--</div>--}}
                {{--</div>--}}
                {{--<div class="col-sm-4">--}}
                    {{--<div class="single-service-item wow fadeInUp" data-wow-delay="1.4s">--}}
                        {{--<h3>SEO Services</h3>--}}
                        {{--<p>Our awesome members are ready to create your dream website project with passion and dedication.</p>--}}
                        {{--<a href="single-service-agency.html" class="readmore-btn">ادامه مطلب...  <i class="fa fa-angle-left"></i></a>--}}
                    {{--</div>--}}
                {{--</div>--}}
                {{--<div class="col-sm-4">--}}
                    {{--<div class="single-service-item wow fadeInUp" data-wow-delay="1.5s">--}}
                        {{--<h3>Content Writing</h3>--}}
                        {{--<p>Our awesome members are ready to create your dream website project with passion and dedication.</p>--}}
                        {{--<a href="single-service-agency.html" class="readmore-btn">ادامه مطلب...  <i class="fa fa-angle-left"></i></a>--}}
                    {{--</div>--}}
                {{--</div>--}}
            {{--</div>--}}
        <div class="clearfix"></div>
        <br>
        <div class="col-sm-10 col-sm-offset-2">
            {{ $posts->render() }}
        </div>

    </div>
    </div>


    @include('partials.footer')

@endsection

resources/views/index/message.blade.php
@extends('layouts.layout')
@section('title')
    پیغام سیستم
@endsection
@section('content')

    @include('partials.header')

    @include('partials.sliderSecond')


    <div class="spacer-10"></div>

    <div class="content-block">
        <div class="container">
            <div class="row">
                <div class="col-md-12 wow fadeInUpBig">

                    <div class="panel panel-{{ $message->type }}">
                        <div class="panel-heading">
                            <h3 class="panel-title">{{ $message->title }}</h3>
                        </div>
                        <div class="panel-body">
                            {!! $message->text !!}
                            <br>
                        </div>
                        <div class="panel-footer">
                            @if(isset($route))
                                <a href="{{ route("$route") }}" class="btn btn-default">{{ $buttonText }}</a>
                            @else
                                <button onclick="goBack()" class="btn btn-default">بازگشت</button>
                            @endif
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    @include('partials.footer')

@endsection
@push('footer')
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
@endpush

resources/views/index/post.blade.php
@extends('layouts.layout')
@section('title')
    @if(isset($post->title))
        {{ $post->title }}
    @else
        antilicense.com
    @endif
@endsection
@push('header')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css">
@endpush
@section('content')

    @include('partials.header')

    @include('partials.sliderSecond')


    <div class="spacer-10"></div>

    <div class="content-block">
        <div class="container">
            <div class="row">
                <div class="col-md-12 wow fadeInUpBig">

                    {!! $post->text !!}

                </div>
            </div>
        </div>
    </div>

    @include('partials.footer')

@endsection
@push('footer')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>

    <script>
        $(".select2").select2({
            dir: "rtl",
            language: "fa",
            width: '100%',
            placeholder: "یکی را انتخاب کنید...",
            tags: false
        });
    </script>
@endpush

resources/views/index/second.blade.php
@extends('layouts.layout')
@section('title')
    {{ $title }}
    {{ $antivirus->name_fa }}
@endsection
@section('content')

    @include('partials.header')

    @include('partials.sliderSecond')

    <div class="spacer-10"></div>
    <div class="spacer-10"></div>
    <hr>
    <div style="font-size: x-large">
        منوی اصلی آنتی ویروس
        {{ $antivirus->name_fa }}:
    </div>


    @include('partials.serviceBox')


    <div class="spacer-100"></div>
    <div class="spacer-100"></div>

    @if($title == 'لایسنس')

        @can('is-editor')
            <a href="{{ route('license.edit', $text['id']) }}">ویرایش</a>
        @endcan

        <div class="content-block">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 wow fadeInRight">
                        <div class="spacer-100"></div>
                        <h3>{{ $title }} {{ $antivirus->name_fa }}<br/>{{ $antivirus->name }}</h3>
                        <div class="spacer-10"></div>

                        @if(isset($text['content_one']))
                            <div>{!! $text['content_one'] !!}</div>
                        @endif
                        @if(isset($text['content_one_vip']))
                            @can('is-vip')
                                <div style="border-bottom: 1px dashed #0b0b0b">{!! $text['content_one_vip'] !!}</div>
                            @else
                                @include('partials.notLoginVip')
                            @endcan
                        @endif
                        @if(isset($text['content_two']))
                            <div>{!! $text['content_two'] !!}</div>
                        @endif
                        @if(isset($text['content_two_vip']))
                            @can('is-vip')
                                <div style="border-bottom: 1px dashed #0b0b0b">{!! $text['content_two_vip'] !!}</div>
                            @else
                                @include('partials.notLoginVip')
                            @endcan
                        @endif
                        @if(isset($text['content_three']))
                            <div>{!! $text['content_three'] !!}</div>
                        @endif
                        @if(isset($text['content_three_vip']))
                            @can('is-vip')
                                <div style="border-bottom: 1px dashed #0b0b0b">{!! $text['content_three_vip'] !!}</div>
                            @else
                                @include('partials.notLoginVip')
                            @endcan
                        @endif
                        @if(isset($text['content_four']))
                            <div>{!! $text['content_four'] !!}</div>
                        @endif
                        @if(isset($text['content_four_vip']))
                            @can('is-vip')
                                <div style="border-bottom: 1px dashed #0b0b0b">{!! $text['content_four_vip'] !!}</div>
                            @else
                                @include('partials.notLoginVip')
                            @endcan
                        @endif
                        @if(isset($text['content_five']))
                            <div style="border-bottom: 1px dashed #0b0b0b">{!! $text['content_five'] !!}</div>
                        @endif

                        <div class="spacer-20"></div>
                    </div>

                    <div class="col-md-6 wow fadeInLeft">
                        <img src="{{ route('index.index') }}/uploads/images/{{ $antivirus->image }}" alt="">
                    </div>
                </div>
            </div>
        </div>

    @elseif($title == 'دیدگاه های' || $title == 'دیدگاه های منتخب')

        <div class="container">
            @foreach($text as $cPost)

                @include('partials.comment')

            @endforeach
        </div>

        @if($title == 'دیدگاه های' && Auth::check())
            <div class="container">
            {!! Form::open(['route'=>['post.store.cpost', $antivirus->id ] ]) !!}
            <!-- فیلد متن: -->
                <div class="form-group {{ $errors->has('text') ? ' has-error' : '' }}">
                    {!! Form::label('text', 'متن:') !!}
                    {!! Form::textarea('text', null, ['class' => 'form-control', 'id'=>'editorcm']) !!}
                    @if ($errors->has('text'))
                        <span class="help-block"><strong>{{ $errors->first('text') }}</strong></span>
                    @endif
                </div>
                <button type="submit" class="btn btn-primary">ثبت دیدگاه</button>
                {!! Form::close() !!}
            </div>
        @endif

    @else
        @if(isset($text))
        @can('is-editor')
            <a href="{{ route('post.edit', $text->id) }}">ویرایش</a>
        @endcan

        <div class="content-block">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 wow fadeInRight">
                        <div class="spacer-100"></div>
                        <h3>{{ $title }} {{ $antivirus->name_fa }}<br/>{{ $antivirus->name }}</h3>
                        <div class="spacer-10"></div>

                        {!! $text->text !!}

                        <div class="spacer-20"></div>
                    </div>

                    <div class="col-md-6 wow fadeInLeft">
                        <img src="{{ route('index.index') }}/uploads/images/{{ $antivirus->image }}" alt="">
                    </div>
                </div>
            </div>
        </div>
        @else
            <div class="content-block">
                <div class="container">
                    <div class="row">
                        در حال حاضر هیچ پستی وجود ندارد.
                    </div>
                </div>
            </div>
        @endif

    @endif

    <div class="spacer-10"></div>
    <div class="spacer-10"></div>

    @include('partials.footer')

@endsection

@if($title == 'دیدگاه های')
    @push('footer')
        <script type="text/javascript" src="{{ asset('editor/basic/ckeditor/ckeditor.js') }}"></script>
        <script type="text/javascript" src="{{ asset('editor/basic/ckeditor/adapters/jquery.js') }}"></script>
        <script>
            $(document).ready(function () {
                $('textarea#editorcm').ckeditor();
            });
        </script>
    @endpush
@endif

resources/views/index/upload.blade.php
@extends('layouts.layout')
@section('content')

    @if(!Auth::check())
        {{ message('ابتدا وارد حساب کاربری خود شوید.', 'login', 'هدایت به صفحه ورود', 'پیغام سیستم', 'danger') }}
    @else
        @can('is-writer')

            @include('partials.header')

            <a href="{{ route('upload.get') }}" class="btn btn-link">صفحه آپلود</a>
            <br><br><br><br><br>

            {!! Form::open(['route'=>['upload.post' ], 'method' => 'post', 'files' => true ]) !!}

            <input type="file" name="file1">
            @if(isset($url1))
                <div>{{ $url1 }}</div>@endif
            <br>
            <input type="file" name="file2">
            @if(isset($url2))
                <div>{{ $url2 }}</div>@endif
            <br>
            <input type="file" name="file3">
            @if(isset($url3))
                <div>{{ $url3 }}</div>@endif
            <br>
            <input type="file" name="file4">
            @if(isset($url4))
                <div>{{ $url4 }}</div>@endif
            <br>
            <input type="file" name="file5">
            @if(isset($url5))
                <div>{{ $url5 }}</div>@endif
            <br>
            <button type="submit" class="btn btn-primary">آپلود</button>

            {!! Form::close() !!}

            <br><br><br><br><br>
            @include('partials.footer')

        @endcan
    @endif
@endsection